# -*- coding: utf-8 -*-
"""GPA_calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-2Gjru6d902h4Wbynsv2xPn9sUvDhoGN
"""

print("Calculator Menu: ")
print("---------------------------- \n")
print("A.) Calculate class grade \n B.) Calculate GPA")
options = input("")

#MENU OPTION B- CALCULATE CLASS GRADE
if options == "A" or options == "a":
  !pip install tabulate
  from tabulate import tabulate

  class1 = input("Enter Class: ")
  assignments = int(input("Enter number of assignments you have grades for: "))
  z = 1
  def calculation():
    global a1
    global max1
    global aw1
    global a1T
    a1 = int(input("Your Grade: "))
    max1 = int(input("Maximum Grade: "))
    aw1 = float(input("Grade weight: "))
    table = [['Your Grade:', 'Max. Grade:', 'Weight:'], [a1, max1, aw1]]
    print(tabulate(table))
  sum = 0
  sum_weights = 0

  for z in range(0, assignments):
    calculation()
    a1T = (a1/max1) * aw1 * 100
    sum += a1T
    sum_weights += aw1
  class_percentage = round(sum/sum_weights, 2)
  lettergrade = ""

  if class_percentage >= 93:
    lettergrade = "A"
  elif class_percentage >= 90:
    lettergrade = "AB"
  elif class_percentage >= 80:
    lettergrade = "B"
  elif class_percentage >= 70:
    lettergrade = "BC"
  elif class_percentage >= 60:
    lettergrade = "C"
  elif class_percentage >= 50:
    lettergrade = "CD"
  else:
    letergrade = "F"

  print("Class Percentage: " + str(class_percentage) + "%" + " | " + "Letter Grade: " + lettergrade)
  print("---------------------------- \n")
  second_calculation = input("Calculate entire GPA? ")

  #MENU 2 OPTION- CALCULATE GPA
  if second_calculation == "Y" or second_calculation == "Yes" or second_calculation == "yes":
    class1 = input("Enter Class 1: ")
    grade1 = float(input("Enter Class 1 Grade: "))
    class1grade = grade1/20 - 1
    if grade1 >= 93:
      lettergrade1 = "A"
    elif grade1 >= 90:
      lettergrade1 = "AB"
    elif grade1 >= 80:
      lettergrade1 = "B"
    elif grade1 >= 70:
      lettergrade1 = "BC"
    elif grade1 >= 60:
      lettergrade1 = "C"
    elif grade1 >= 50:
      lettergrade1 = "CD"
    else:
      letergrade1 = "F"
    print("Class 1: " + class1 + " |", "Grade: " + str(grade1) + "%" + " | " + lettergrade1)
    print("---------------------------- \n")

    class2 = input("Enter Class 2: ")
    grade2 = float(input("Enter Class 2 Grade: "))
    class2grade = grade2/20 - 1
    if grade2 >= 93:
      lettergrade1 = "A"
    elif grade2 >= 90:
      lettergrade1 = "AB"
    elif grade2 >= 80:
      lettergrade1 = "B"
    elif grade2 >= 70:
      lettergrade1 = "BC"
    elif grade2 >= 60:
      lettergrade1 = "C"
    elif grade2 >= 50:
      lettergrade1 = "CD"
    else:
      letergrade1 = "F"
    print("Class 2: " + class2 + " |", "Grade: " + str(grade2) + "%" + " | " + lettergrade1)
    print("---------------------------- \n")

    class3 = input("Enter Class 3: ")
    grade3 = float(input("Enter Class 3 Grade: "))
    class3grade = grade3/20 - 1
    if grade3 >= 93:
      lettergrade1 = "A"
    elif grade3 >= 90:
      lettergrade1 = "AB"
    elif grade3 >= 80:
      lettergrade1 = "B"
    elif grade3 >= 70:
      lettergrade1 = "BC"
    elif grade3 >= 60:
      lettergrade1 = "C"
    elif grade3 >= 50:
      lettergrade1 = "CD"
    else:
      letergrade1 = "F"
    print("Class 3: " + class3 + " |", "Grade: " + str(grade3) + "%" + " | " + lettergrade1)
    print("---------------------------- \n")

    class4 = input("Enter Class 4: ")
    grade4 = float(input("Enter Class 4 Grade: "))
    class4grade = grade4/20 - 1
    if grade4 >= 93:
      lettergrade1 = "A"
    elif grade4 >= 90:
      lettergrade1 = "AB"
    elif grade4 >= 80:
      lettergrade1 = "B"
    elif grade4 >= 70:
      lettergrade1 = "BC"
    elif grade4 >= 60:
      lettergrade1 = "C"
    elif grade4 >= 50:
      lettergrade1 = "CD"
    else:
      letergrade1 = "F"
    print("Class 4: " + class4 + " |", "Grade: " + str(grade4) + "%" + " | " + lettergrade1)
    print("---------------------------- \n")

    addclass = input("Add another class? ")
    if addclass == "Y" or addclass == "yes" or addclass == "Yes":
      class5 = input("Enter Class 5: ")
      grade5 = float(input("Enter Class 5 Grade: "))
      class5grade = grade5/20 - 1
      if grade5 >= 93:
        lettergrade1 = "A"
      elif grade5 >= 90:
        lettergrade1 = "AB"
      elif grade5 >= 80:
        lettergrade1 = "B"
      elif grade5 >= 70:
        lettergrade1 = "BC"
      elif grade5 >= 60:
        lettergrade1 = "C"
      elif grade5 >= 50:
        lettergrade1 = "CD"
      else:
        letergrade1 = "F"
      print("Class 5: " + class5 + " |", "Grade: " + str(grade5) + "%" + " | " + lettergrade1)
      print("---------------------------- \n")
      addclass2 = input("Add another class? ")
      if addclass2 == "Y" or addclass2 == "yes" or addclass2 == "Yes":
        class6 = input("Enter Class 6: ")
        grade6 = float(input("Enter Class 6 Grade: "))
        class6grade = grade6/20 - 1
        if grade6 >= 93:
          lettergrade1 = "A"
        elif grade6 >= 90:
          lettergrade1 = "AB"
        elif grade6 >= 80:
          lettergrade1 = "B"
        elif grade6 >= 70:
          lettergrade1 = "BC"
        elif grade6 >= 60:
          lettergrade1 = "C"
        elif grade6 >= 50:
          lettergrade1 = "CD"
        else:
          letergrade1 = "F"
        print("Class 6: " + class6 + " |", "Grade: " + str(grade6) + "%" + " | " + lettergrade1)
        print("---------------------------- \n")
        total_gpa3 = round((class1grade + class2grade + class3grade + class4grade + class5grade + class6grade) / 6, 2)
        print("Total GPA: " + str(total_gpa3))
      else:
        total_gpa1 = round((class1grade + class2grade + class3grade + class4grade + class5grade) / 5, 2)
        print("Total GPA: " + str(total_gpa1))
    else:
      total_gpa2 = round((class1grade + class2grade + class3grade + class4grade) / 4, 2)
      print("Total GPA: " + str(total_gpa2))
  
#MENU OPTION B
else:
  class1 = input("Enter Class 1: ")
  grade1 = float(input("Enter Class 1 Grade: "))
  class1grade = grade1/20 - 1
  if grade1 >= 93:
    lettergrade1 = "A"
  elif grade1 >= 90:
    lettergrade1 = "AB"
  elif grade1 >= 80:
    lettergrade1 = "B"
  elif grade1 >= 70:
    lettergrade1 = "BC"
  elif grade1 >= 60:
    lettergrade1 = "C"
  elif grade1 >= 50:
    lettergrade1 = "CD"
  else:
    letergrade1 = "F"
  print("Class 1: " + class1 + " |", "Grade: " + str(grade1) + "%" + " | " + lettergrade1)
  print("---------------------------- \n")

  class2 = input("Enter Class 2: ")
  grade2 = float(input("Enter Class 2 Grade: "))
  class2grade = grade2/20 - 1
  if grade2 >= 93:
    lettergrade1 = "A"
  elif grade2 >= 90:
    lettergrade1 = "AB"
  elif grade2 >= 80:
    lettergrade1 = "B"
  elif grade2 >= 70:
    lettergrade1 = "BC"
  elif grade2 >= 60:
    lettergrade1 = "C"
  elif grade2 >= 50:
    lettergrade1 = "CD"
  else:
    letergrade1 = "F"
  print("Class 2: " + class2 + " |", "Grade: " + str(grade2) + "%" + " | " + lettergrade1)
  print("---------------------------- \n")

  class3 = input("Enter Class 3: ")
  grade3 = float(input("Enter Class 3 Grade: "))
  class3grade = grade3/20 - 1
  if grade3 >= 93:
    lettergrade1 = "A"
  elif grade3 >= 90:
    lettergrade1 = "AB"
  elif grade3 >= 80:
    lettergrade1 = "B"
  elif grade3 >= 70:
    lettergrade1 = "BC"
  elif grade3 >= 60:
    lettergrade1 = "C"
  elif grade3 >= 50:
    lettergrade1 = "CD"
  else:
    letergrade1 = "F"
  print("Class 3: " + class3 + " |", "Grade: " + str(grade3) + "%" + " | " + lettergrade1)
  print("---------------------------- \n")

  class4 = input("Enter Class 4: ")
  grade4 = float(input("Enter Class 4 Grade: "))
  class4grade = grade4/20 - 1
  if grade4 >= 93:
    lettergrade1 = "A"
  elif grade4 >= 90:
    lettergrade1 = "AB"
  elif grade4 >= 80:
    lettergrade1 = "B"
  elif grade4 >= 70:
    lettergrade1 = "BC"
  elif grade4 >= 60:
    lettergrade1 = "C"
  elif grade4 >= 50:
    lettergrade1 = "CD"
  else:
    letergrade1 = "F"
  print("Class 4: " + class4 + " |", "Grade: " + str(grade4) + "%" + " | " + lettergrade1)
  print("---------------------------- \n")

  addclass = input("Add another class? ")
  if addclass == "Y" or addclass == "yes" or addclass == "Yes":
    class5 = input("Enter Class 5: ")
    grade5 = float(input("Enter Class 5 Grade: "))
    class5grade = grade5/20 - 1
    if grade5 >= 93:
      lettergrade1 = "A"
    elif grade5 >= 90:
      lettergrade1 = "AB"
    elif grade5 >= 80:
      lettergrade1 = "B"
    elif grade5 >= 70:
      lettergrade1 = "BC"
    elif grade5 >= 60:
      lettergrade1 = "C"
    elif grade5 >= 50:
      lettergrade1 = "CD"
    else:
      letergrade1 = "F"
    print("Class 5: " + class5 + " |", "Grade: " + str(grade5) + "%" + " | " + lettergrade1)
    print("---------------------------- \n")
    addclass2 = input("Add another class? ")
    if addclass2 == "Y" or addclass2 == "yes" or addclass2 == "Yes":
      class6 = input("Enter Class 6: ")
      grade6 = float(input("Enter Class 6 Grade: "))
      class6grade = grade6/20 - 1
      if grade6 >= 93:
        lettergrade1 = "A"
      elif grade6 >= 90:
        lettergrade1 = "AB"
      elif grade6 >= 80:
        lettergrade1 = "B"
      elif grade6 >= 70:
        lettergrade1 = "BC"
      elif grade6 >= 60:
        lettergrade1 = "C"
      elif grade6 >= 50:
        lettergrade1 = "CD"
      else:
        letergrade1 = "F"
      print("Class 6: " + class6 + " |", "Grade: " + str(grade6) + "%" + " | " + lettergrade1)
      print("---------------------------- \n")
      total_gpa3 = round((class1grade + class2grade + class3grade + class4grade + class5grade + class6grade) / 6, 2)
      print("Total GPA: " + str(total_gpa3))
    else:
      total_gpa1 = round((class1grade + class2grade + class3grade + class4grade + class5grade) / 5, 2)
      print("Total GPA: " + str(total_gpa1))
  else:
    total_gpa2 = round((class1grade + class2grade + class3grade + class4grade) / 4, 2)
    print("Total GPA: " + str(total_gpa2))