# -*- coding: utf-8 -*-
"""HW2 - Variables & Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10nfHG2EsSL3w_cA1AkxSsKTJ2-ncTXxg

# Homework Assignment #2 (50 points)

**Write a function that solve the problem and display the answer. Use variable for each quantity.
Write a short function description of what is your function is doing.**

## Q1. **Car Loan (10 pts)** 

If A dollars is borrowed at *r%* interest compounded monthly to purchase a car with monthly payments for *n* years, then the monthly payment is given by the formula:
$$monthlypayment =\frac{A * i}{1 - (1 + i)^{(-12 * n)}}$$
where *i = r/12* . Write a function with three parameters (amount of loan, interest rate (%), number of years), then the function will calculate monthly payment after the user call this function with specifying the amount of the loan, the interest rate, and the numbers of years. <br>

---
**For example**

The function looks like the following:
```python
def monthly_payment(A, r, n):
  ''' Returns the monthly payment for car loan
      Input:
        a: amount of load
        r: annually interest rate, a dollars is borrowed at r%
        n: number of years
  ''' 
```

After you successfully define this function, you can test your function by the  following parameters: <br>
* amount of loan (A): 12000 <br>
* interest rate (r%): 6.4% <br>
* number of years(n): 5 <br>

Then monthly payment is: 234.23

You can pass these parameters into your function, and **you are expected to get the following:**
```python
>>> monthly_payment(12000, 0.064, 5)
234.232109628263
```
"""

# Q1: Please start your work here
def monthly_payment(A, r, n):
  equation = (A*(r/12))/(1-(1+(r/12))**(-12*n))
  print("The monthly payment is: " + str(round(equation, 2)))

monthly_payment(12000, 0.064, 5)

"""## **Q2. Analize a Sentance (10 pts)** 
Write a function that displays the first and last words of a sentence input by the user. Assume that the only punctuation is a period at the end of the sentance and words are separated by white space. *(Hint: find the first and the last white spaces and then use appropriate indexes to print requred words)*

---
**For example**

The function looks like the following:
```python
def first_last_word(sent):
  '''Returns the first and last words fo a sentence input by the user
     Input:
        sent: a sentence input by the user
  '''
```

You can test your function by the test case below:
sentence = 'Whatever you are be a good one'. The output of ``first_last_word(sentence)`` is expected to be ``(Whatever, one)``<br>

Here's what the ouput would look like if you call this function with the test case.
```python
>>> sentence = 'Whatever you are be a good one'
>>> first_last_word(sentence)
('whatever', 'one')
```

"""

def first_last_word(sentence):
  a = sentence.split()
  print(a[0], a[-1])

sentence = 'Whatever you are be a good one'

first_last_word(sentence)

"""## **Q3. Cost of Electricity (10 pts)** 

The cost of electricity used by a device is given by the formula
cost of electricity (in dollars) = (wattage of device * hours used)/(1,000*cost per kWh(in cents)), where kWh is an abbreviations for "kilowat hours". The cost per kWh of electricity varies with locality. Suppose the current average cost of electricity for a residential customer in the United States is 11.76 cents per kWh. Write a function that allows the user to calculate the cost of operating an electric device such as 100 wattage light bulb turned on for entire month of June. The function would asked user to enter the following information:<br>

Enter wattage: <br>
Enter number of hours used: <br>
Enter price per kWh in cents: <br>
After the data entry, the function would show the cost (rounded to 2 decimal points with $ sign) of operatic this device. <br>

(***Hint: you can format the output either by print, float or str formatting***)

---
**For example** 

The function would look like:
```python
def cost_electricity():
  '''
  The function will ask user to enter wattage, the number of hours
  used, and the price per KWH in cents, and return the cost (rounded
  to 2 decimal points with $ sign) of operatic this device.
  '''
```
Here is the test case:
* Enter wattage: 100
* Enter number of hours used: 744
* Enter price per KWH in cents: 11.76

The cost of electricity used by this device is: $6.33

Here's what the output would look like if user call this function and enter the test case:
```python
>>> cost_electricity()
>>> Enter wattage: 100
>>> Enter number of hours used: 744
>>> Enter price per KWH in cents: 11.76
The cost of electricity used by this device is: $6.33
```
**Make sure that outputs have the same formatting as showed in the example above.**
"""

# Q3: Please start your code here

def cost_electricity():
  w = int(input("Enter wattage: "))
  h = int(input("Enter number of hours used: "))
  p = float(input("Enter price per KWH in cents: "))
  equation = (w * h) / (1000 * p)
  print("The cost of electricity used by this device is: " + "$" + (str(round(equation, 2))))

cost_electricity()

"""## **Q4. Change in Salary （10 pts)** 
A common misconception is that if you receive three successive 5% pay increases, the your original salary will have increased by 15.76% ($1.05^3$) . Write a function (``new_salary``) to calculate your new salary after receive three successive r% pay increase. Request a base salary and r% pay increase as parameters and output is the salary after receiving three successive r% pay raises and the percentage changes in salary. <br>


---
**For example**
The function would look like:
```python
def new_salary(base_salary, r):
  '''Returns the new salary after receiving three successive r% pay
     and the percentage changes in salary.
     Input:
        base_salary: the old salary
        r: r% pay increase
  '''
```
Here is the test case:
* Enter beginning salary: 35000
* Pay increase rate: 5% <br>

The new salary: $40,516.88 and Change: 15.76% <br>

Here's what the output would look like if the user call this function with parameters in the test case.
```python
>>> new_salary(35000, 0.05)
The new salary: $40,516.88
The change is: 15.76%
```

**Make sure that outputs have the same formatting as showed in the example above.**
"""

# Q4: Please start your code here
def new_salary(base_salary, r):
  base_salary1 = int(input("Enter beginning salary: "))
  r = float(input("Pay increase rate: "))

  #Calculate first pay increase.
  base_salary2 = (base_salary * r) + base_salary
  #Calculate second pay increase
  base_salary2 = (base_salary2 * r) + base_salary2
  #Calculate third pay increase
  finalbase_salary = (base_salary2 * r) + base_salary2
  #Insert comma into new salary
  format_salary = "{:,}".format(finalbase_salary)
  print("The new salary: " + "$" + (str(format_salary)))

  #Calculate the change
  change = (finalbase_salary - base_salary) / (base_salary) * 100
  print("The change is: " + "%" + (str(round(change, 2))))

new_salary(35000, 0.05)

"""## **Q5. Present Value (10 pts)** 
The present value of f dollars at interest rate r% compounded annually for n years is the amount of money that must be invested now in order to growth f dollars (called the future value) in n years where the interest rate is r% per year. The formula for present value is
 $$"present value (PV)" =  \frac{f}{(1 + r/100)^n}$$ 

Write a function to calculate the present value of investment with three parameters: future value, interest rate, and numbers of years. <br>

---
**For example:**

You need complete the following function:
```python
def present_value(f_value, r, n):
  ''' Returns present value of fo dollars at interest rate r% compoundly
      annually for n years
      Input:
          f_value: future value
          r: interest rate r%
          n: years
  '''
```
You can test your function with the following information:
* future value: 10000 <br>
* interest rate (as %): 4 <br>
* number of years: 6 <br>

Then, the present value is $7,903.15 <br>

Here's what the output would look like if the user call this function with parameters/arguments in the test case.

```python
>>> present_value(10000, 4, 6)
The present value is $7,903.15
```

**Make sure that outputs have the same formatting as showed in the example above.** 
"""

# Q5: Please start your code here
def present_value(f_value, r, n):
  equation = f_value / (1+r/100)** n
  equation = (round(equation, 2))
  print("The present value is " + "$" + str("{:,}".format(equation)))

present_value(10000, 4, 6)