# -*- coding: utf-8 -*-
"""Week_2_HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12jCg413k5sYU_vGQ_K5SCS9XAAs9fdku

# Homework Assignment #1 (50 points)

**Write a program that has one line of code for each step (Q1-Q4).**

## Q1.  **Identify Data Types(8 points)** 

Create each variable and identify associated data type from the list below:
*  a = [1, 2, 5]
*  b = 12
*  c = True
*  d = {'A':'AAA', 'B':'BBB'}
*  e = (4,7)
*  f = {4,7}
*  g = 16.7
*  h = 'Hi'
"""

a = [1, 2, 5]
type(a)

b = 12
type(b)

c = True
type(c)

d = {'A':'AAA', 'B':'BBB'}
type(d)

e = (4,7)
type(e)

f = {4,7}
type(f)

g = 16.7
type(g)

h = 'Hi'
type(h)

"""## Q2. **Identify Expression Data Types (6 points)**
Identify and print each expression's data type from the list below:

*  int(1.5)
*  12+0.1
*  (5 < 4) and (13 > 6)
*  round(13.455, 0)
*  55//3
*  55%3
"""

type(int(1.5))

type(12+0.1)

type((5 < 4) & (13>6))

type(round(13.455, 0))

type(55//3)

type(55%3)

"""## Q3. **Saving Account (10 points)**
The following steps calculate the balance at the end of three years when $100 is deposited at the beginning of each year in savings account at 5% interest compounded annually.
*  a) Create the variable ``balance`` and assign it the value 100.
*  b) Increase the value of variable ``balance`` by 5%, and add 100 to it.
*  c) Increase the value of variable ``balance`` by 5%, and add 100 to it.
*  d) Increase the value of variable ``balance`` by 5%.
*  e) Display the value of the variable ``balance`` (rounded to two decimal places).
"""

#Starting amount
balance = 100

#Year 1 interest- 100 invested + additional 100 added per instructions
balance = balance + (balance * 0.05) + 100

#Year 2 additional interest- 100 invested 
balance = balance + (balance * 0.05) + 100

#Year 3 additional interest- 100 invested
balance = balance + (balance * 0.05)

print(round(balance, 2))

"""## Q4. **Profit from stock (8 points)**
The following steps calculate the percentage profit from the sale of stock.
*  a) Create the variable ``purchasePrice`` and assign it the value 10.
*  b) Create the variable ``sellingPrice`` and assign it the value 15.
*  c) Create the variable ``percentProfit`` and assign it the value the difference between ``sellingPrice`` and ``purchasePrice`` divided by ``purchasePrice`` and multiply by 100.
*  d) Display the value of the variable ``percentProfit``.

"""

purchasePrice = 10
sellingPrice = 15
percentProfit = ((sellingPrice - purchasePrice)/(purchasePrice) * (100))
print(percentProfit)

"""**Write a program that solve the problem and display the answer. Use variable for each quantity (Q5-Q6).**

## Q5. **Gas Mileage (9 points)**
A motorist wants to determine her gas mileage. At 23,352 miles (on the odometer) the tank is filled. At 23,695 miles the tank is filled again with 14 galons. How many miles per gallon did car average between the two fillings?
"""

miles1 = 23352
miles2 = 23695
gallons = 14
trip = (miles2 - miles1)/ (gallons)
print("Miles per gallon car averaged: " + str(trip))

"""## Q6. **Calories (9 points)**
A large bar(2.6 oz) of Dark Chocolate contains about 388 calories. You would need to walk 47 minutes to burn 170 calories. How long do you need to walk to burn off calories from one medium bar (1.45 oz) of Dark Chocolate ?
"""

#Use proportion of a large bar (2.6 oz) to calculate how many calories are in a medium 1.45 oz bar
large = 1.45 * (388/2.6)

#Calculate how many calories per minute someone burns off by walking
calmins = 170 / 47

#Divide two portions                        
print(("Total Minutes To Burn Off Calories For Medium Bar: ") + (str(round(large / calmins))))

"""## Bouns Question. **Number guessing games (10 points)**
*Note: The point you earned from this bouns question will add to your homework assginemnt. However, the maximum points for this assignment is 50 points in total.*

In this question, you need write a program that complete the following tasks:


*   The program chooses a random integer between 0 and 20 (inclusive)
*   Then ask the user to guess what number has been chosen.
*   Each time the user enters a guess, the program indicates one fo the following:
> - Too high
> - Too low
> - Just right
*   If the user gusses correctly, the program exists. Otherwise, the user is asked to try again
*   The program only exists after the user guesses correctly.

***Hint: the flow of this game is very similar as the PRS game that we demonstrated in the class.***
"""

import random  # import the random module to generate a random number

answer = random.randint(0,20)   # the program randomly chooses a integer between 0 and 10
while True:
  user_guess = int(input('What is your guess? '))  # take the input from yours

  #-------------------- Plese complete from this point -------------------------
  if user_guess == answer:
    print("Just right")
    break
  
  if user_guess > answer:
    print("Too high")

  if user_guess < answer:
    print("Too low")